import re

# Load fetch_proxy.py content
with open('c:/Users/Bog_1/OneDrive/Desktop/Fetch Free Proxy/fetch_proxy.py', encoding='utf-8') as f:
    content = f.read()

existing_urls = set(re.findall(r'https?://[^\s\'"<>`\)]+', content))

# Load the user's input from a file or just hardcode it here
user_text = """
https://raw.githubusercontent.com/rxyzqc/SOCKS5-Proxy-Gen/main/socks5sites.txt
https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/http.txt
https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks4.txt
https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks5.txt
https://raw.githubusercontent.com/HyperBeats/proxy-list/main/http.txt
https://raw.githubusercontent.com/HyperBeats/proxy-list/main/socks4.txt
https://raw.githubusercontent.com/HyperBeats/proxy-list/main/socks5.txt
https://raw.githubusercontent.com/manuGMG/proxy-365/main/SOCKS5.txt
https://raw.githubusercontent.com/databay-labs/free-proxy-list/main/http.txt
https://raw.githubusercontent.com/databay-labs/free-proxy-list/main/socks4.txt
https://raw.githubusercontent.com/databay-labs/free-proxy-list/main/socks5.txt
https://raw.githubusercontent.com/hproxy-com/free-proxy-list/main/http.txt
https://raw.githubusercontent.com/hproxy-com/free-proxy-list/main/https.txt
https://raw.githubusercontent.com/hproxy-com/free-proxy-list/main/socks4.txt
https://raw.githubusercontent.com/hproxy-com/free-proxy-list/main/socks5.txt
https://raw.githubusercontent.com/GGboogie/PROXY-List/main/http.txt
https://raw.githubusercontent.com/GGboogie/PROXY-List/main/socks4.txt
https://raw.githubusercontent.com/GGboogie/PROXY-List/main/socks5.txt
https://raw.githubusercontent.com/caliphdev/Proxy-List/master/http.txt
https://raw.githubusercontent.com/caliphdev/Proxy-List/master/socks4.txt
https://raw.githubusercontent.com/caliphdev/Proxy-List/master/socks5.txt
https://raw.githubusercontent.com/BlackSnowDot/proxylist-update-every-minute/main/http.txt
https://raw.githubusercontent.com/BlackSnowDot/proxylist-update-every-minute/main/https.txt
https://raw.githubusercontent.com/BlackSnowDot/proxylist-update-every-minute/main/socks4.txt
https://raw.githubusercontent.com/BlackSnowDot/proxylist-update-every-minute/main/socks5.txt
https://raw.githubusercontent.com/Dev-Team-V/Free-Proxies/main/http.txt
https://raw.githubusercontent.com/Dev-Team-V/Free-Proxies/main/socks4.txt
https://raw.githubusercontent.com/Dev-Team-V/Free-Proxies/main/socks5.txt
https://raw.githubusercontent.com/EnoT-Hub/proxy-list/main/http.txt
https://raw.githubusercontent.com/EnoT-Hub/proxy-list/main/socks4.txt
https://raw.githubusercontent.com/EnoT-Hub/proxy-list/main/socks5.txt
https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/http.txt
https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks4.txt
https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks5.txt
https://raw.githubusercontent.com/RX4096/proxy-list/main/online/http.txt
https://raw.githubusercontent.com/RX4096/proxy-list/main/online/socks4.txt
https://raw.githubusercontent.com/RX4096/proxy-list/main/online/socks5.txt
https://raw.githubusercontent.com/mertguvencli/http-proxy-list/main/proxy-list/data.txt
https://raw.githubusercontent.com/Bardiafa/Proxy-Leecher/main/proxies.txt
https://raw.githubusercontent.com/AyoubSirai/proxy-list/main/proxy-list.txt
https://raw.githubusercontent.com/joshua-ns/Proxy-Scraper/master/proxies.txt
https://raw.githubusercontent.com/yixiu001/proxy-list/main/proxy.txt
https://hproxy.com/api/proxy-list?format=txt&protocol=http
https://hproxy.com/api/proxy-list?format=txt&protocol=https
https://hproxy.com/api/proxy-list?format=txt&protocol=socks4
https://hproxy.com/api/proxy-list?format=txt&protocol=socks5
https://api.proxyscan.io/download?type=http
https://api.proxyscan.io/download?type=https
https://api.proxyscan.io/download?type=socks4
https://api.proxyscan.io/download?type=socks5
https://t.me/s/ProxySocks5Free
https://t.me/s/proxies_http
https://t.me/s/Proxy_List_2026
https://t.me/s/Proxy_Scrap
https://t.me/s/elite_proxies_list
https://t.me/s/socks_proxy_net
https://t.me/s/http_proxies_list
https://t.me/s/free_proxy_world
https://t.me/s/proxyhub_net
https://html.duckduckgo.com/html/?q=site:pastebin.com+"HTTP/1.1+200+OK"+"8080"&df=d
https://html.duckduckgo.com/html/?q=site:rentry.co+"http_proxies"+"port"&df=d
https://html.duckduckgo.com/html/?q=site:justpaste.it+"proxy+list"+"elite"&df=d
https://html.duckduckgo.com/html/?q=site:fofa.info+"HTTP+Proxy"+"X-Forwarded-For"&df=w
https://html.duckduckgo.com/html/?q=site:zoomeye.org+"squid"+"port:3128"&df=w
https://html.duckduckgo.com/html/?q=site:shodan.io+"HTTP/1.1+200+OK"+"Server:+squid"&df=w
https://raw.githubusercontent.com/B4RC0DE-TM/proxy-list/main/SOCKS5.txt
https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks5.txt
https://api.openproxylist.xyz/socks5.txt
https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt
https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks5.txt
https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt
https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt
https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt
https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt
https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt
https://raw.githubusercontent.com/BlackSnowDot/proxylist-update-every-minute/main/socks.txt
https://proxyspace.pro/socks5.txt
https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5
https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5
https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all&simplified=true
http://worm.rip/socks5.txt
http://www.socks24.org/feeds/posts/default
https://www.proxy-list.download/api/v1/get?type=socks5
https://www.proxyscan.io/download?type=socks5
https://www.my-proxy.com/free-socks-5-proxy.html
https://raw.githubusercontent.com/LalatinaHub/Proxy-List/main/http.txt
https://raw.githubusercontent.com/parserpp/ip_ports/main/proxyinfo.txt
https://raw.githubusercontent.com/itsallnans/proxy-list/main/proxies.txt
https://raw.githubusercontent.com/Toffanello/Free-Proxy-List/main/http.txt
https://raw.githubusercontent.com/ahmadhasibul/Proxy-List/main/http.txt
https://raw.githubusercontent.com/z2x-team/Proxy-List/main/http.txt
https://raw.githubusercontent.com/Zullis/free-proxy-list/main/http.txt
https://raw.githubusercontent.com/andig/proxylist/master/proxy.txt
https://raw.githubusercontent.com/Spp001/Proxy-List/main/proxies.txt
https://raw.githubusercontent.com/TheLime1/Validity/main/data/socks4.txt
https://raw.githubusercontent.com/TheLime1/Validity/main/data/socks5.txt
https://raw.githubusercontent.com/TheLime1/Validity/main/data/https.txt
https://www.proxy-list.download/api/v1/get?type=http&anon=anonymous
https://www.proxy-list.download/api/v1/get?type=http&anon=transparent
https://www.proxy-list.download/api/v1/get?type=https&anon=anonymous
https://www.proxy-list.download/api/v1/get?type=https&anon=transparent
https://www.proxy-list.download/api/v1/get?type=socks4&anon=anonymous
https://www.proxy-list.download/api/v1/get?type=socks5&anon=anonymous
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=http&port=80
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=http&port=8080
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=http&port=3128
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks5&port=1080
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks4&port=4145
https://t.me/s/free_proxies_socks5
https://t.me/s/proxylist_24
https://t.me/s/proxies_daily
https://t.me/s/proksi_list
https://t.me/s/Proxy_List_world
https://t.me/s/proxy_socks5_free_vip
https://t.me/s/socks5_proxy_list_http
https://t.me/s/v2ray_vpn_configs
https://html.duckduckgo.com/html/?q=site:controlc.com+"socks5"+intext:"1080"&df=d
https://html.duckduckgo.com/html/?q=site:pastefs.com+"http+proxy"+intext:"8080"&df=d
https://html.duckduckgo.com/html/?q=site:hastebin.com+"proxy+list"+intext:"8080"&df=d
https://html.duckduckgo.com/html/?q=site:dpaste.com+"socks5"+intext:"1080"&df=d
https://html.duckduckgo.com/html/?q=site:fofa.info+"Server:+tinyproxy"&df=w
https://html.duckduckgo.com/html/?q=site:fofa.info+"Server:+3proxy"&df=w
https://html.duckduckgo.com/html/?q=site:zoomeye.org+"3proxy"+"port:1080"&df=w
https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/http.txt
https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks4.txt
https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks5.txt
https://raw.githubusercontent.com/prxchk/proxy-list/main/elite/http.txt
https://raw.githubusercontent.com/prxchk/proxy-list/main/elite/socks4.txt
https://raw.githubusercontent.com/prxchk/proxy-list/main/elite/socks5.txt
https://cdn.jsdelivr.net/gh/proxifly/free-proxy-list@main/proxies/anonymity/elite/data.txt
https://cdn.jsdelivr.net/gh/proxifly/free-proxy-list@main/proxies/anonymity/anonymous/data.txt
https://html.duckduckgo.com/html/?q=site:gitee.com+"proxy-list"+"http"&df=w
https://html.duckduckgo.com/html/?q=site:gitee.com+"socks5"+"1080"&df=w
https://html.duckduckgo.com/html/?q=site:gitlab.com+"proxies.txt"+"HTTP/1.1"&df=w
https://html.duckduckgo.com/html/?q=site:gitlab.com+"socks5.txt"+"port"&df=w
https://t.me/s/free_proxy_ipv4
https://t.me/s/proxylist4all
https://t.me/s/premium_proxy_list
https://t.me/s/proxy_server_list
https://t.me/s/shadowsocks_free
https://t.me/s/v2ray_custom
https://t.me/s/Best_Proxies_List
https://raw.githubusercontent.com/Kitsun3Sec/ProxyList/master/http.txt
https://raw.githubusercontent.com/Kitsun3Sec/ProxyList/master/socks4.txt
https://raw.githubusercontent.com/Kitsun3Sec/ProxyList/master/socks5.txt
https://raw.githubusercontent.com/Nomad0x0/Awesome-Proxies/main/proxies.txt
https://raw.githubusercontent.com/Toffanello/Free-Proxy-List/main/socks4.txt
https://raw.githubusercontent.com/Toffanello/Free-Proxy-List/main/socks5.txt
https://raw.githubusercontent.com/Vann-Dev/proxy-list/main/proxies/socks5.txt
https://www.proxy-list.download/api/v1/get?type=http&country=US
https://www.proxy-list.download/api/v1/get?type=http&country=GB
https://www.proxy-list.download/api/v1/get?type=http&country=DE
https://www.proxy-list.download/api/v1/get?type=socks5&country=US
https://www.proxy-list.download/api/v1/get?type=socks5&country=RU
https://html.duckduckgo.com/html/?q=intitle:"index+of"+inurl:"proxy.txt"&df=w
https://html.duckduckgo.com/html/?q=intitle:"index+of"+inurl:"proxies/http.txt"&df=w
https://html.duckduckgo.com/html/?q=intitle:"index+of"+inurl:"socks5.json"&df=w
https://checkerproxy.net/api/archive/
https://raw.githubusercontent.com/NotUnko/Free-Proxy-List/main/proxies.txt
https://raw.githubusercontent.com/TheVoidGroup/Proxy-List/main/http.txt
https://raw.githubusercontent.com/TheVoidGroup/Proxy-List/main/socks4.txt
https://raw.githubusercontent.com/TheVoidGroup/Proxy-List/main/socks5.txt
https://raw.githubusercontent.com/SlavaBogatov/proxy-list/main/proxies.txt
https://html.duckduckgo.com/html/?q=intitle:"SilverBullet+Logs"+"proxy"&df=w
https://html.duckduckgo.com/html/?q=intitle:"OpenBullet+Logs"+"proxies"&df=w
https://html.duckduckgo.com/html/?q=site:0bin.net+"socks5"&df=d
https://html.duckduckgo.com/html/?q=site:zerobin.net+"8080"+OR+"3128"&df=d
https://html.duckduckgo.com/html/?q=site:paste.ee+"socks5"+intext:"1080"&df=d
https://html.duckduckgo.com/html/?q=site:paste.ubuntu.com+"HTTP/1.1+200+OK"&df=d
https://html.duckduckgo.com/html/?q=site:ideone.com+"proxy"+intext:"http"&df=d
https://t.me/s/proxylist_premium
https://t.me/s/free_proxies_list_2026
https://t.me/s/MTProto_Proxy_List
https://t.me/s/Socks5_Proxy_List_Vip
https://t.me/s/Proxy_List_Free_VIP
https://t.me/s/vpn_proxy_custom
https://t.me/s/working_proxies
https://api.proxyscrape.com/v2/?request=displayproxies&protocol=http&timeout=1000&country=all&ssl=yes&anonymity=elite
https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5&timeout=1000&country=all&anonymity=elite
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=http&speed=slow&anonymityLevel=transparent
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks5&speed=slow
https://html.duckduckgo.com/html/?q=ext:log+"HTTP/1.1+200+OK"+"X-Forwarded-For"&df=w
https://html.duckduckgo.com/html/?q=intitle:"index+of"+"proxies.txt"&df=d
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=http&uptime=90
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=https&uptime=90
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks4&uptime=90
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks5&uptime=90
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=http&ipType=ipv6
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks5&ipType=ipv6
https://html.duckduckgo.com/html/?q=ext:yaml+"proxies:"+"type:+socks5"+"server:"&df=w
https://html.duckduckgo.com/html/?q=ext:yaml+"proxies:"+"type:+http"+"server:"&df=w
https://html.duckduckgo.com/html/?q=site:github.com+inurl:"clash.yaml"+"proxies"&df=w
https://html.duckduckgo.com/html/?q=site:slexy.org+"socks5://"+port&df=w
https://html.duckduckgo.com/html/?q=site:paste2.org+"HTTP/1.1+200+OK"&df=w
https://html.duckduckgo.com/html/?q=site:rentry.co+"vmess://"&df=w
https://html.duckduckgo.com/html/?q=site:telegra.ph+"proxy+list"+intext:"8080"&df=w
https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt
https://raw.githubusercontent.com/MuhammadBahaa2001/Proxy-List/main/http.txt
https://raw.githubusercontent.com/T0x1cA114cK/Proxy-List/main/socks5.txt
https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4.txt
https://raw.githubusercontent.com/Bardiafa/Proxy-Leecher/main/good.txt
https://raw.githubusercontent.com/fahimkawsar/proxy-list/main/proxy.txt
https://t.me/s/free_proxy_socks5_http
https://t.me/s/proxy_list_premium_free
https://t.me/s/ProxyScraperList
https://t.me/s/proxies_for_all
https://t.me/s/openbullet_proxies
https://www.proxy-list.download/api/v1/get?type=http&port=8080
https://www.proxy-list.download/api/v1/get?type=http&port=3128
https://www.proxy-list.download/api/v1/get?type=socks5&port=1080
https://www.proxy-list.download/api/v1/get?type=socks4&port=4145
https://t.me/s/iran_proxy
https://t.me/s/proxy_iran_socks5
https://t.me/s/v2rayng_org
https://t.me/s/v2rayng_vpn
https://t.me/s/free_v2ray_config
https://t.me/s/V2ray_Alpha
https://t.me/s/Shadowsocks_Proxy_List
https://t.me/s/vpn_fail
https://t.me/s/vpn_fail_socks5
https://t.me/s/free_proxy_list_socks5
https://html.duckduckgo.com/html/?q=site:pastie.org+"socks5"+port&df=d
https://html.duckduckgo.com/html/?q=site:paste.fo+"HTTP/1.1"+intext:"8080"&df=d
https://html.duckduckgo.com/html/?q=site:textbin.net+"proxy"+"8080"&df=d
https://html.duckduckgo.com/html/?q=site:throwbin.io+"socks5"&df=d
https://html.duckduckgo.com/html/?q=site:justpaste.it+"socks4"&df=d
https://t.me/s/HTTP_Proxy_List_Free
https://t.me/s/Socks4_Proxy_List_Free
https://t.me/s/Socks5_Proxy_List_Free
https://t.me/s/HTTP_Proxy_List_Vip
https://t.me/s/socks5_proxy_list_vip
https://t.me/s/proxies_anonymous_elite
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=http&anonymityLevel=elite&port=80
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks5&anonymityLevel=elite&port=1080
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks4&anonymityLevel=elite&port=4145
https://raw.githubusercontent.com/Wannabe1337/Proxy-List/main/proxies.txt
https://raw.githubusercontent.com/yuzhen123/Free-Proxy-List/main/proxies.txt
https://raw.githubusercontent.com/sppeding/proxy-list/main/proxies.txt
https://raw.githubusercontent.com/obfuskator/proxy-list/main/proxy.txt
https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/http.txt
https://raw.githubusercontent.com/tuanminpay/live-proxy/master/all.txt
https://html.duckduckgo.com/html/?q=ext:txt+"HTTP/1.1+200+OK"+"Via:"+"Proxy"&df=w
https://html.duckduckgo.com/html/?q=ext:txt+"socks5"+"auth:none"&df=w
https://api.proxyscrape.com/v2/?request=displayproxies&protocol=http&timeout=500&country=all&ssl=all&anonymity=elite
https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks4&timeout=500&country=all&anonymity=elite
https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5&timeout=500&country=all&anonymity=elite
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=speed&sort_type=asc&protocols=http
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=speed&sort_type=asc&protocols=https
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=speed&sort_type=asc&protocols=socks4
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=speed&sort_type=asc&protocols=socks5
https://html.duckduckgo.com/html/?q=site:pastebin.pl+"socks5"+intext:"1080"&df=d
https://html.duckduckgo.com/html/?q=site:pastebin.pl+"http+proxy"+intext:"8080"&df=d
https://html.duckduckgo.com/html/?q=site:cl1p.net+"socks5"&df=d
https://html.duckduckgo.com/html/?q=site:cl1p.net+"proxy+list"+intext:"http"&df=d
https://html.duckduckgo.com/html/?q=site:ghostbin.me+"socks5://"+port&df=d
https://html.duckduckgo.com/html/?q=site:ghostbin.me+"HTTP/1.1+200+OK"&df=d
https://raw.githubusercontent.com/ViggoPro/proxy-list/main/proxies.txt
https://raw.githubusercontent.com/Deybuhnt/proxylist/main/proxies.txt
https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt
https://raw.githubusercontent.com/Zullis/free-proxy-list/main/socks4.txt
https://raw.githubusercontent.com/Zullis/free-proxy-list/main/socks5.txt
https://raw.githubusercontent.com/EnoT-Hub/proxy-list/main/https.txt
https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/socks4.txt
https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/socks5.txt
https://t.me/s/proxy_list_world_free
https://t.me/s/free_proxy_list_vip
https://t.me/s/proxy_socks5_http_https_vip
https://t.me/s/proxies_scraper
https://t.me/s/socks5_proxy_scraper
https://t.me/s/proxy_list_100
https://t.me/s/proxylist_update_24
https://html.duckduckgo.com/html/?q=site:rentry.co+"SOCKS4"+intext:"1080"&df=w
https://html.duckduckgo.com/html/?q=site:pastebin.com+ext:txt+"socks5"+intext:"1080"&df=d
https://html.duckduckgo.com/html/?q=site:pastebin.com+ext:txt+"http_proxies"&df=d
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks5&country=RU
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks5&country=UA
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks5&country=KZ
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=http&country=RU
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=http&country=UA
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=http&google=true
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=https&google=true
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks4&google=true
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=lastChecked&sort_type=desc&protocols=socks5&google=true
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=speed&sort_type=asc&protocols=socks5&google=true
https://proxylist.geonode.com/api/proxy-list?limit=500&sort_by=speed&sort_type=asc&protocols=http&google=true
https://t.me/s/Singbox_Config
https://t.me/s/xray_proxy
https://t.me/s/vless_vmess_trojan_shadowsocks
https://t.me/s/Xray_VPN_Configs
https://t.me/s/reality_config
https://t.me/s/Singbox_Nodes
https://html.duckduckgo.com/html/?q=site:github.com+"socks5"+ext:txt&df=d
https://html.duckduckgo.com/html/?q=site:github.com+"http_proxy"+ext:txt&df=d
https://html.duckduckgo.com/html/?q=site:github.com+"proxies"+ext:txt+"8080"&df=d
https://html.duckduckgo.com/html/?q=site:notes.io+"socks5"&df=d
https://html.duckduckgo.com/html/?q=site:paste.rs+"HTTP/1.1+200"&df=d
https://html.duckduckgo.com/html/?q=site:snippet.host+"proxy"&df=d
http://pubproxy.com/api/proxy?limit=5&format=txt&http=true&country=BR
http://pubproxy.com/api/proxy?limit=5&format=txt&http=true&country=IN
http://pubproxy.com/api/proxy?limit=5&format=txt&http=true&country=ID
http://pubproxy.com/api/proxy?limit=5&format=txt&socks5=true&country=RU
https://openproxyspace.com/api/proxy?protocol=socks5
https://openproxyspace.com/api/proxy?protocol=http
https://html.duckduckgo.com/html/?q=ext:json+"proxies"+"server"+"port"&df=w
https://t.me/s/free_proxy_socks5_http_https
https://t.me/s/proxylist_2026_free
https://t.me/s/socks4_proxy_list
https://t.me/s/proxy_list_elite_anonymous
"""

new_urls = set(re.findall(r'https?://[^\s\'"<>`\)]+', user_text))

missing = new_urls - existing_urls
missing = [u for u in missing if 't.me' not in u and 'duckduckgo' not in u]

print(f"Total new unique regular URLs requested: {len(new_urls)}")
print(f"Missing from fetch_proxy.py (excluding telegram and duckduckgo search queries): {len(missing)}")
with open('missing_urls.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(missing))
