import re

with open('extracted_prompt.py', 'r', encoding='utf-8') as f:
    text = f.read()

# Extract Python code blocks (if they are in markdown, or just lines that look like valid python)
# Since the prompt might just be raw text with python interspersed, let's write a parser to extract the `extend` or list logic.
lines = text.split('\n')
code_lines = []
in_code = True # Assume code by default until we hit non-code text that causes SyntaxError? No.

# Let's just find all URLs with regex! That's the easiest way!
urls = []
for match in re.finditer(r"'(https?://[^']+)'\s*,\s*'([^']+)'", text):
    url, proto = match.group(1), match.group(2)
    urls.append((url, proto))
    
# What about the ones generated by loops?
# The loops use f-strings: f'https://www.proxy-list.download/api/v1/get?type=http&country={country}'
# So regex on raw text will miss them if we don't execute python.

# Let's extract everything between `# === ШЕСТАЯ ПАРТИЯ` and the end, remove non-python lines.
start = text.find('# === ШЕСТАЯ ПАРТИЯ')
if start == -1:
    start = text.find('TOP_COUNTRIES')
    
python_code = """
SOURCES = []
"""
# Add the loops code manually based on what I saw
python_code += text[start:]

# Let's write the python_code to a file and fix syntax errors manually
with open('temp_code.py', 'w', encoding='utf-8') as f:
    f.write(python_code)
